project_id = "qvnkuqvdfolktpnhhbxc"

[functions.analyze-color]
verify_jwt = false

[functions.analyze-wrong]
verify_jwt = false

[functions.report-to-human]
verify_jwt = false

[functions.color-analysis-cache]
verify_jwt = false